### ISSUE TITLE
Copy V2 content

### ISSUE THREAD

**Issue by kendall1978** [kendall1978/begin-again-V3#1]
## To-Do
- [x] Create views folder
  - This was removed, so that we can follow Nuxt best practices and utilize it better
- [x] Use sections from V2 as new "view" components
- [x] Make sure the footer is below the content viewport
