### ISSUE TITLE
Firebase admin login

### ISSUE THREAD

**Issue by kendall1978** [kendall1978/begin-again-V3#10]
##TODO
- [ ] Add admin accounts that can edit data on the website
- [ ] write firestore rules that only allow specific account ID's to login and edit data
- [ ] build login page
- [ ] make sure routing is setup so that only admins can access the admin page
