### ISSUE TITLE
Firebase database setup

### ISSUE THREAD

**Issue by kendall1978** [kendall1978/begin-again-V3#2]
## To-Do
- [x] Use data.json from v2 to map firebase collections
- [x] Connect firebase to pinia
- [x] Map collections to pinia state
