### ISSUE TITLE
Drone shot of building

### ISSUE THREAD

**Issue by kendall1978** [kendall1978/begin-again-V3#3]
## To-Do
- [ ] Work with stakeholders to get drone shots of the building
- [ ] Add photo to Firebase storage
- [ ] Map firebase storage to collections
- [ ] Use drone shot as a hero image
