### ISSUE TITLE
Frontend UI Changes

### ISSUE THREAD

**Issue by colelong101** [kendall1978/begin-again-V3#4]
# To-Do
### Header
- [ ] Modern look with social icons
- [x] Paypal Icon
- [ ] New Font and incorporate logo

### Hero
- [ ] Large background image, with opaque overlay
- [ ] Hero Text

WIP for other sections
