### ISSUE TITLE
Firebase update functions and forms

### ISSUE THREAD

**Issue by kendall1978** [kendall1978/begin-again-V3#9]
## To-Do
- [ ] Write Firebase functions in the main store that create and update records
- [x] build table in the back-end of the website that can display all records and corresponding data
- [ ] build forms for each collection in Firebase
